"""add report_generations table

Revision ID: 457c45a85369
Revises: 00fc2ebcd830
Create Date: 2026-06-09 17:32:50.301243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457c45a85369'
down_revision: Union[str, Sequence[str], None] = '00fc2ebcd830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('data_snapshot', sa.LargeBinary(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generation_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("layout IN ('pc', 'mobile')", name='ck_report_layout'),
    sa.CheckConstraint("status IN ('pending', 'generating', 'completed', 'failed')", name='ck_report_status'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_generations_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_generations_person_id'))

    op.drop_table('report_generations')
    # ### end Alembic commands ###
